### ISSUE TITLE
How do I get my model to work?

### ISSUE THREAD

**Issue by scfpalmer** [RangeShifter/RangeShifter-software-and-documentation#1]
This is a test issue to see whether I get a prompt response!

**Comment by damariszurell** [comment]
Who do you want to respond?
;-)

**Comment by scfpalmer** [comment]
Thank you, Damaris, you are the winner!

However, this time I did not receive a notification of the issue, despite not having altered my settings (as far as I am aware) since the compiler issue last week. Did anyone else receive notification?

Steve
